# Generated by Django 4.1.6 on 2023-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Elelctrical', 'Electrical'), ('Sports', 'Sports'), ('Grooming', 'Grooming')], max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
