# Generated by Django 4.1.6 on 2023-07-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Electrical', 'Electrical'), ('Sports', 'Sports'), ('Grooming', 'Grooming')], max_length=128),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
        ),
    ]
