# Generated by Django 4.1.6 on 2023-07-06 12:22

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_category_type_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='otp',
            field=models.CharField(default=ecommerce.models.generate_default_otp, max_length=6),
        ),
        migrations.AddField(
            model_name='category',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
